#!/bin/zsh

grep --color=always -r postulate $(git ls-files) $1 | grep -v "HIT$" |\
 grep -v "Universe levels$" | grep -v "Univalence axiom$" |\
 grep -v "tutorial/README.md" | grep -v "findpostulates"
